import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import dynamic from "next/dynamic";

// Refer this for element import
// import nextDynamicImport from '../../utils/nextDynamicImport'
// const Button = nextDynamicImport('Button');


const ReactAppComponent = dynamic(() => import("remote/Home").catch(
  () => {
    return () => <h2 className={styles.h2}>Please run remote app on port other than 3000!</h2>
  }),{
  ssr: false,
});

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.h2}>
          Welcome to <a href="https://nextjs.org">Next (host)!</a>
        </h1>
        {/* Refer this for element import */}
        {/* <Button label="This is btn"/>   */}
        {<ReactAppComponent />}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
